=== sarakristo-prog/DAW-LMISGI-SaraKristo/cifp.dtd
<!ELEMENT cifp (alumno | profesor)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT teléfono (#PCDATA)>
<!ELEMENT dirección (#PCDATA)>

<!ELEMENT alumno (nombre, apellidos, fecha_nacimiento?, correo?, teléfono?, dirección?, fecha_matrícula, curso)>
<!ATTLIST alumno id NMTOKEN #REQUIRED>
<!ELEMENT fecha_matrícula (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

<!ELEMENT profesor (nombre, apellidos, fecha_nacimiento?, correo?, teléfono?, dirección?, fecha_incorporación, departamento, asignatura*)>
<!ATTLIST profesor id NMTOKEN #REQUIRED>
<!ELEMENT fecha_incorporación (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>

<!ELEMENT asignatura (nombre_asignatura, fecha_inicio?, fecha_final?)>
<!ATTLIST asignatura 
    id_asignatura NMTOKEN #REQUIRED
    ciclo (DAM|DAW|ASIX|SMX|SEIA|ER|AUT) #REQUIRED>
<!ELEMENT nombre_asignatura (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_final (#PCDATA)>

=== sarakristo-prog/DAW-LMISGI-SaraKristo/cifp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM "cifp.dtd">
<cifp>
    <alumno id="1">
        <nombre>Sara</nombre>
        <apellidos>García</apellidos>
        <teléfono>600112233</teléfono>
        <dirección>Calle Mayor 10</dirección>
        <fecha_matrícula>2024-09-01</fecha_matrícula>
        <curso>DAW</curso>
    </alumno>
    <profesor id="101">
        <nombre>Juan</nombre>
        <apellidos>Pérez</apellidos>
        <fecha_incorporación>2020-01-15</fecha_incorporación>
        <departamento>Informática</departamento>
        <asignatura id_asignatura="50" ciclo="DAW">
            <nombre_asignatura>Desarrollo Web en Entorno Cliente</nombre_asignatura>
        </asignatura>
    </profesor>
</cifp>
